version: '3.8'
services:
  backend:
    build: backend
    command: "corepack pnpm start:dev"
    ports:
      - "3000:3000"

  frontend:
    build: frontend
    command: "corepack pnpm dev --host"
    ports:
      - "5173:5173"
